-- AI Customer Support Automation
-- PostgreSQL schema required by the n8n workflows.
-- Run in the Supabase SQL Editor when setting up a new database.

-- Customers are matched by email in the Human Escalation Workflow.
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Generates the numeric part of ticket numbers, formatted by the workflow as AUR-0001, AUR-0002, etc.
-- If this sequence already exists, IF NOT EXISTS preserves its current value.
CREATE SEQUENCE IF NOT EXISTS public.support_ticket_number_seq
    AS BIGINT
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number TEXT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES public.customers(id),
    customer_request TEXT NOT NULL,
    category TEXT,
    priority TEXT,
    proposed_response TEXT,
    validation_reason TEXT,
    status TEXT NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Stores resumable workflow state when an escalation is waiting for customer identity.
CREATE TABLE IF NOT EXISTS public.support_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL UNIQUE,
    customer_id BIGINT REFERENCES public.customers(id),
    status TEXT NOT NULL,
    pending_action TEXT,
    original_customer_request TEXT,
    category TEXT,
    priority TEXT,
    proposed_response TEXT,
    validation_reason TEXT,
    conversation_context TEXT,
    customer_name TEXT,
    customer_email TEXT,
    active_ticket_id BIGINT REFERENCES public.support_tickets(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security on customer-support tables.
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_conversations ENABLE ROW LEVEL SECURITY;